"use strict";
const electron = require("electron");
electron.contextBridge.exposeInMainWorld("electronAPI", {
  // 资源数据
  loadData: () => electron.ipcRenderer.invoke("load-data"),
  saveData: (data) => electron.ipcRenderer.invoke("save-data", data),
  getDataPath: () => electron.ipcRenderer.invoke("get-data-path"),
  exportData: (data) => electron.ipcRenderer.invoke("export-data", data),
  importData: () => electron.ipcRenderer.invoke("import-data"),
  openExternal: (url) => electron.ipcRenderer.invoke("open-external", url),
  marketplaceFetch: (url) => electron.ipcRenderer.invoke("marketplace-fetch", url),
  marketplaceSkillImport: (url) => electron.ipcRenderer.invoke("marketplace-skill-import", url),
  // MCP 管理
  mcpList: () => electron.ipcRenderer.invoke("mcp-list"),
  mcpEnable: (name) => electron.ipcRenderer.invoke("mcp-enable", name),
  mcpDisable: (name) => electron.ipcRenderer.invoke("mcp-disable", name),
  mcpConnect: (name) => electron.ipcRenderer.invoke("mcp-connect", name),
  mcpDisconnect: (name) => electron.ipcRenderer.invoke("mcp-disconnect", name),
  mcpCallTool: (name, toolName, args) => electron.ipcRenderer.invoke("mcp-call-tool", name, toolName, args),
  mcpGetStatus: (name) => electron.ipcRenderer.invoke("mcp-get-status", name),
  mcpCheckUpdate: (name) => electron.ipcRenderer.invoke("mcp-check-update", name),
  mcpAdd: (name, config) => electron.ipcRenderer.invoke("mcp-add", name, config),
  mcpRemove: (name) => electron.ipcRenderer.invoke("mcp-remove", name),
  mcpUpdate: (name, config) => electron.ipcRenderer.invoke("mcp-update", name, config),
  mcpGetConfigPath: () => electron.ipcRenderer.invoke("mcp-get-config-path"),
  resourceCenterList: () => electron.ipcRenderer.invoke("resource-center-list"),
  resourceCenterMcpAdd: (name, config) => electron.ipcRenderer.invoke("resource-center-mcp-add", name, config),
  resourceCenterSkillCreate: (name, content) => electron.ipcRenderer.invoke("resource-center-skill-create", name, content),
  // AI 翻译
  aiTranslate: (text) => electron.ipcRenderer.invoke("ai-translate", text),
  aiExplainSkill: (content) => electron.ipcRenderer.invoke("ai-explain-skill", content),
  aiGetSettings: () => electron.ipcRenderer.invoke("ai-get-settings"),
  aiSaveSettings: (settings) => electron.ipcRenderer.invoke("ai-save-settings", settings),
  aiFetchModels: () => electron.ipcRenderer.invoke("ai-fetch-models"),
  // Skills 管理
  skillsGetGlobal: () => electron.ipcRenderer.invoke("skills-get-global"),
  skillsDiscoverWork: () => electron.ipcRenderer.invoke("skills-discover-work"),
  skillsGetProject: (projectPath) => electron.ipcRenderer.invoke("skills-get-project", projectPath),
  skillsGet: (skillPath) => electron.ipcRenderer.invoke("skills-get", skillPath),
  skillsCreate: (name, content, scope, projectPath) => electron.ipcRenderer.invoke("skills-create", name, content, scope, projectPath),
  skillsUpdate: (skillPath, content) => electron.ipcRenderer.invoke("skills-update", skillPath, content),
  skillsDelete: (skillPath) => electron.ipcRenderer.invoke("skills-delete", skillPath),
  skillsGetGlobalPath: () => electron.ipcRenderer.invoke("skills-get-global-path"),
  skillsReadFile: (skillPath, fileName) => electron.ipcRenderer.invoke("skills-read-file", skillPath, fileName),
  skillsSaveFile: (skillPath, fileName, content) => electron.ipcRenderer.invoke("skills-save-file", skillPath, fileName, content),
  skillsDeleteFile: (skillPath, fileName) => electron.ipcRenderer.invoke("skills-delete-file", skillPath, fileName),
  skillsSelectProject: () => electron.ipcRenderer.invoke("skills-select-project"),
  skillsImportFolder: (scope, projectPath) => electron.ipcRenderer.invoke("skills-import-folder", scope, projectPath),
  skillsImportDirectory: (scope, projectPath) => electron.ipcRenderer.invoke("skills-import-directory", scope, projectPath),
  skillsImportZip: (scope, projectPath) => electron.ipcRenderer.invoke("skills-import-zip", scope, projectPath),
  skillsGenerateAiSummary: (skillPath, content) => electron.ipcRenderer.invoke("skills-generate-ai-summary", skillPath, content),
  skillsSaveAiSummary: (skillPath, summary) => electron.ipcRenderer.invoke("skills-save-ai-summary", skillPath, summary),
  skillsCopy: (sourcePath, targetScope, targetProjectPath) => electron.ipcRenderer.invoke("skills-copy", sourcePath, targetScope, targetProjectPath),
  skillsMove: (sourcePath, targetScope, targetProjectPath) => electron.ipcRenderer.invoke("skills-move", sourcePath, targetScope, targetProjectPath),
  // Droids 管理
  droidsGetGlobal: () => electron.ipcRenderer.invoke("droids-get-global"),
  droidsDiscoverWork: () => electron.ipcRenderer.invoke("droids-discover-work"),
  droidsGetProject: (projectPath) => electron.ipcRenderer.invoke("droids-get-project", projectPath),
  droidsGet: (droidPath) => electron.ipcRenderer.invoke("droids-get", droidPath),
  droidsCreate: (data, scope, projectPath) => electron.ipcRenderer.invoke("droids-create", data, scope, projectPath),
  droidsUpdate: (droidPath, data) => electron.ipcRenderer.invoke("droids-update", droidPath, data),
  droidsDelete: (droidPath) => electron.ipcRenderer.invoke("droids-delete", droidPath),
  droidsGetGlobalPath: () => electron.ipcRenderer.invoke("droids-get-global-path"),
  droidsSaveConfig: (droidName, config) => electron.ipcRenderer.invoke("droids-save-config", droidName, config),
  droidsGetTools: () => electron.ipcRenderer.invoke("droids-get-tools"),
  droidsGetToolCategories: () => electron.ipcRenderer.invoke("droids-get-tool-categories"),
  droidsSelectProject: () => electron.ipcRenderer.invoke("droids-select-project"),
  droidsGenerateAiSummary: (droidPath, droidName, content) => electron.ipcRenderer.invoke("droids-generate-ai-summary", droidPath, droidName, content),
  droidsCopy: (sourcePath, targetScope, targetProjectPath) => electron.ipcRenderer.invoke("droids-copy", sourcePath, targetScope, targetProjectPath),
  droidsMove: (sourcePath, targetScope, targetProjectPath) => electron.ipcRenderer.invoke("droids-move", sourcePath, targetScope, targetProjectPath),
  // Prompts 管理
  promptsGetAll: () => electron.ipcRenderer.invoke("prompts-get-all"),
  promptsGet: (promptPath) => electron.ipcRenderer.invoke("prompts-get", promptPath),
  promptsCreate: (name, content, description, category, linkedResources) => electron.ipcRenderer.invoke("prompts-create", name, content, description, category, linkedResources),
  promptsUpdate: (promptPath, content, description, category, linkedResources) => electron.ipcRenderer.invoke("prompts-update", promptPath, content, description, category, linkedResources),
  promptsDelete: (promptPath) => electron.ipcRenderer.invoke("prompts-delete", promptPath),
  promptsGetPath: () => electron.ipcRenderer.invoke("prompts-get-path"),
  promptsGetCount: () => electron.ipcRenderer.invoke("prompts-get-count"),
  // Rules 管理
  rulesGetGlobal: () => electron.ipcRenderer.invoke("rules-get-global"),
  rulesGetProject: (projectPath) => electron.ipcRenderer.invoke("rules-get-project", projectPath),
  rulesGet: (rulePath) => electron.ipcRenderer.invoke("rules-get", rulePath),
  rulesCreate: (name, content, scope, projectPath, description, category, priority, globs, linkedResources) => electron.ipcRenderer.invoke("rules-create", name, content, scope, projectPath, description, category, priority, globs, linkedResources),
  rulesUpdate: (rulePath, content, description, category, priority, globs, linkedResources) => electron.ipcRenderer.invoke("rules-update", rulePath, content, description, category, priority, globs, linkedResources),
  rulesDelete: (rulePath) => electron.ipcRenderer.invoke("rules-delete", rulePath),
  rulesGetGlobalPath: () => electron.ipcRenderer.invoke("rules-get-global-path"),
  rulesGetGlobalCount: () => electron.ipcRenderer.invoke("rules-get-global-count"),
  rulesSelectProject: () => electron.ipcRenderer.invoke("skills-select-project"),
  rulesCopy: (sourcePath, targetScope, targetProjectPath) => electron.ipcRenderer.invoke("rules-copy", sourcePath, targetScope, targetProjectPath)
});
